// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGfa3G5GM0EzRB2wsnlQFGsYWWL9Z6qo',
    appId: '1:274607135930:web:741a1a24d8671601b67683',
    messagingSenderId: '274607135930',
    projectId: 'tripbud-3799b',
    authDomain: 'tripbud-3799b.firebaseapp.com',
    storageBucket: 'tripbud-3799b.firebasestorage.app',
    measurementId: 'G-77NGQ1B5KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM32vPNCrSxJp4hpx4yEMaa_ujVW9n0BE',
    appId: '1:274607135930:android:5a41ecbd9cebbdb3b67683',
    messagingSenderId: '274607135930',
    projectId: 'tripbud-3799b',
    storageBucket: 'tripbud-3799b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNXu2rQ-F1GR2PgwxKcCrg_P7JowmxEk',
    appId: '1:274607135930:ios:f48b3dcb31559d92b67683',
    messagingSenderId: '274607135930',
    projectId: 'tripbud-3799b',
    storageBucket: 'tripbud-3799b.firebasestorage.app',
    iosClientId: '274607135930-15sk52sqgg3mh13tnc6fs8se3pchj0ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripBud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBNXu2rQ-F1GR2PgwxKcCrg_P7JowmxEk',
    appId: '1:274607135930:ios:f48b3dcb31559d92b67683',
    messagingSenderId: '274607135930',
    projectId: 'tripbud-3799b',
    storageBucket: 'tripbud-3799b.firebasestorage.app',
    iosClientId: '274607135930-15sk52sqgg3mh13tnc6fs8se3pchj0ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripBud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARGfa3G5GM0EzRB2wsnlQFGsYWWL9Z6qo',
    appId: '1:274607135930:web:81e0710d63a43bc6b67683',
    messagingSenderId: '274607135930',
    projectId: 'tripbud-3799b',
    authDomain: 'tripbud-3799b.firebaseapp.com',
    storageBucket: 'tripbud-3799b.firebasestorage.app',
    measurementId: 'G-X16VFRNSL4',
  );

}